### PR TITLE
Add clang-tidy targets to project

### PR DESCRIPTION
**Pull request by phako**
- add .clang-tidy file containing our settings and some configs
   according to our coding guidelines
 - add two explicit targets for calling just lint or lint-and-fix
 - add enableable support for CMakes "native" clang-tidy support (makes
   build super-slow)

### CODE REVIEW

**Review by mhier — APPROVED** [review]

**Comment by phako** [comment]
I'm currently fighting with a regression that the fixer tool introduced and it is super hard to debug, I think I will add some kind of mode that does a git commit after having processed each file, for supported bisecting

**Comment by mhier** [comment]
Won't many changes require to be done consistency across multiple files?

**Comment by phako** [comment]
Yes. I am not sure how that all works together

**Comment by phako** [comment]
Added the tool that does a git commit after running applying the fixes. It's not prefect as it feeds from compile_commands.json and thus the first commit will include loads of fixes from the included files

Also includes a fix to run the linters from the source folder, so they pick up .clang-format and .clang-tidy of the project

**Review by mhier — APPROVED** [review]

**Pull request merged**
