### PR TITLE
Draft: Allow install of Find* files to share-cmake

### PR DESCRIPTION
**Pull request by phako**
The versioned folder is a Ubuntu speciality, other systems do not really like that folder

### CODE REVIEW

**Comment by phako** [comment]
CMake Error at cmake/create_cmake_config_files.cmake:100:
  Parse error.  Expected "(", got newline with text "

  ".
Call Stack (most recent call first):
  CMakeLists.txt:112 (include)


-- Configuring incomplete, errors occurred!

**Comment by phako** [comment]
Actually... I don't think we even need the Find* files anymore...

**Comment by killenb** [comment]
I am not sure how the config-based module lookup works, but when I am manually configuring against my own installation I have to use "-DCMAKE_MODULE_PATH=~/ChimeraTK_installation/share/cmake-3.16/modules" for ChimeraTK to be found.

**Comment by phako** [comment]
This is obsolete after the move to import targets

**Pull request closed without merging**
